<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidat extends \App\Entity\Candidat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'prenom_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'tel_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'genre_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'domaine_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'photo_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'linkedin', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'experiences', 'id'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'prenom_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'tel_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'genre_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'domaine_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'photo_candidat', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'linkedin', '' . "\0" . 'App\\Entity\\Candidat' . "\0" . 'experiences', 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPrenomCandidat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomCandidat', []);

        return parent::getPrenomCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomCandidat(string $prenom_candidat): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomCandidat', [$prenom_candidat]);

        return parent::setPrenomCandidat($prenom_candidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(\DateTimeInterface $date_naissance): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$date_naissance]);

        return parent::setDateNaissance($date_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelCandidat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelCandidat', []);

        return parent::getTelCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelCandidat(string $tel_candidat): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelCandidat', [$tel_candidat]);

        return parent::setTelCandidat($tel_candidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenreCandidat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenreCandidat', []);

        return parent::getGenreCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenreCandidat(string $genre_candidat): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenreCandidat', [$genre_candidat]);

        return parent::setGenreCandidat($genre_candidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaineCandidat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaineCandidat', []);

        return parent::getDomaineCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaineCandidat(string $domaine_candidat): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaineCandidat', [$domaine_candidat]);

        return parent::setDomaineCandidat($domaine_candidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoCandidat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoCandidat', []);

        return parent::getPhotoCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoCandidat($photo_candidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoCandidat', [$photo_candidat]);

        return parent::setPhotoCandidat($photo_candidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedin', []);

        return parent::getLinkedin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkedin(string $linkedin): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedin', [$linkedin]);

        return parent::setLinkedin($linkedin);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperiences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperiences', []);

        return parent::getExperiences();
    }

    /**
     * {@inheritDoc}
     */
    public function addExperience(\App\Entity\ExperienceProfissionnelle $experience): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExperience', [$experience]);

        return parent::addExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExperience(\App\Entity\ExperienceProfissionnelle $experience): \App\Entity\Candidat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExperience', [$experience]);

        return parent::removeExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $username): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmPassword', []);

        return parent::getConfirmPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmPassword($confirm_password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmPassword', [$confirm_password]);

        return parent::setConfirmPassword($confirm_password);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

}
