<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMXQyK76\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMXQyK76/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMXQyK76.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMXQyK76\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMXQyK76\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MXQyK76',
    'container.build_id' => '9bcd284d',
    'container.build_time' => 1593453373,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMXQyK76');
